language: node_js
node_js:
- 5.3
install:
- npm install
- npm install -g cypress-cli
before_script:
- npm start -- --silent &
script:
- cypress run --record
env:
  matrix:
    secure: lVr0oMxabpU/VRFd/JWF+7qbvKQLY1uUVnJPfiCLCbh4Tv1Sc6YOnFYzxgoZ/d7OoySzil18CRIj7ldvICoxqYg1E2krnVgJzr65UBC08Kt0jt4KwdOn1Q/cQZ22hdM+dx2OQGoJWefc+H1/AuQ+khcVQFaDTKOC30WWnRFnTTabjC9h10zc97TuO+SwPxlPHthO0lvZfGiY3depeu76hiRy5tjPjqeOsBvCw12iUO2FAWk2t3ZfpTFAn0ND1dF4bW0rgVUSZmeGQCaUdfSPjFGyh7qM+ro2gLbME8wNVnasn2JkjGhJXZYqYL47SbTWV0hzKIDwnkKDrDkG6dbqr6FP8qPJvtF0xFStDRek+LhuxTIaR+7o3o15uyUgWb8McFWdaY/qbfs4KBhVvVn3rVhqlMZw10PPrHerE+wfoUUBWdfBuOKYaA19auhox3/MrOCb27e1uIsOCXZYxCRcncvZ9XVEmZvfr0EjzGqVCMg0/4MKji4mMhKTUyKvnWkaQCIaC/xxLOE8m+tCSzKqWXlSGT+tnLePe6JSrTGit8sUke/R9xBv4LUOIzjGN3PrAGGJo3yBDdevNkPWb1Pgpvbwe80ikw9iMUyT9JQrgm0oKvzKDU756WNDb0RVzJZ1x+qyAuaD8zP1+Yo/eXZNWmxALqoqNExg3M9+fNnipcs=
